# Generated by Django 3.2 on 2021-05-13 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=20000, null=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('input_data', models.ManyToManyField(blank=True, related_name='problem_input_data', to='codes.DataFileModel')),
                ('input_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_input_type', to='codes.codemodel')),
                ('output_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_output_type', to='codes.codemodel')),
                ('problem_postprocess', models.ManyToManyField(blank=True, to='codes.CodeModel')),
            ],
        ),
    ]
