# Generated by Django 3.2 on 2021-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210513_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='aaaaaaaaa',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
