# Generated by Django 3.2 on 2021-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
        ('problems', '0003_problemmodel_aaaaaaaaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmodel',
            name='problem_postprocess',
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='postprocesses',
            field=models.ManyToManyField(blank=True, related_name='problem_postprocess', to='codes.CodeModel'),
        ),
    ]
