# Generated by Django 3.2 on 2021-05-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20210514_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemmodel',
            old_name='postprocesses',
            new_name='postprocess',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='aaaaaaaaa',
        ),
    ]
