# Generated by Django 3.2 on 2021-05-13 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(blank=True, max_length=20000, null=True)),
                ('requirements', models.CharField(blank=True, max_length=20000, null=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='_codes_codemodel_dependencies_+', to='codes.CodeModel')),
            ],
        ),
        migrations.CreateModel(
            name='DataFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to='data')),
                ('flags', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_data', models.CharField(blank=True, max_length=20000, null=True)),
                ('status', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('stdout', models.CharField(blank=True, max_length=20000, null=True)),
                ('errors', models.CharField(blank=True, max_length=20000, null=True)),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.codemodel')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.datafilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='codemodel',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='code_files', to='codes.DataFileModel'),
        ),
    ]
